import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {dark} from "@clerk/themes";
import { Toaster } from "@/components/ui/toaster"
import {
  ClerkProvider,
 
} from '@clerk/nextjs'
import { SpeedInsights } from "@vercel/speed-insights/next"
import StoreProvider from "@/storeProvider";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["500", "700", "900", "400"]
});

export const metadata: Metadata = {
  title: "StarshinerS women online store",
  description: "Generated by create next app",
  icons: {
    icon: ""
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{
         baseTheme: dark,
         layout: {
          logoImageUrl: "https://stcnt.starshiners.ro/img/logo-StarShinerS-2.svg",
          socialButtonsVariant: "iconButton"
        }
      }} >
       
         
             <body className={roboto.className}> 
             <StoreProvider>
            
                {children} 
                <SpeedInsights /> 
                <Toaster />
              </StoreProvider>
              </body>
             
        
     
      </ClerkProvider>
      
    </html>
  );
}
